### ISSUE TITLE
redshift-gtk info dialog is sometimes blank

### ISSUE THREAD

**Issue by doublejinitials** [jonls/redshift#417] opened 2017-01-02 08:58 UTC
I'm using Manjaro with GNOME and redshift 1.11. If the "info" window is closed by using the window controls instead of the close button at the bottom, subsequent attempts to open it result in only a blank dialog being shown with no text or buttons. This persists until redshift-gtk is restarted.

Every time the dialog is shown, regardless of if it is blank, the following message is printed

    Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

If it is blank, then this message is also printed

    Gtk-CRITICAL **: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

**Comment by Cxpher** [comment] 2017-01-03 20:22
I can confirm this issue exists on Arch. Probably due to the fact that it's not mapped with a transient parent to begin with. You can't see this immediately. 

I had to launch redshift-gtk and wait for up to more than a day to see it. But i've also seen it in less than 10 mins. It's intermittent. But below is what happens in the terminal when it does.

[xxxx@mars ~]redshift-gtk
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(redshift-gtk:11301): Gtk-CRITICAL **: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(redshift-gtk:11301): Gtk-CRITICAL **: _gtk_container_get_border_width_set: assertion 'GTK_IS_CONTAINER (container)' failed

(redshift-gtk:11301): Gtk-CRITICAL **: gtk_container_set_border_width: assertion 'GTK_IS_CONTAINER (container)' failed

(redshift-gtk:11301): Gtk-CRITICAL **: _gtk_container_set_border_width_set: assertion 'GTK_IS_CONTAINER (container)' failed

(redshift-gtk:11301): Gtk-CRITICAL **: _gtk_box_get_spacing_set: assertion 'GTK_IS_BOX (box)' failed

(redshift-gtk:11301): Gtk-CRITICAL **: gtk_box_set_spacing: assertion 'GTK_IS_BOX (box)' failed

(redshift-gtk:11301): Gtk-CRITICAL **: _gtk_box_set_spacing_set: assertion 'GTK_IS_BOX (box)' failed

(redshift-gtk:11301): Gtk-CRITICAL **: gtk_button_box_get_layout: assertion 'GTK_IS_BUTTON_BOX (widget)' failed

(redshift-gtk:11301): Gtk-CRITICAL **: gtk_box_set_spacing: assertion 'GTK_IS_BOX (box)' failed

(redshift-gtk:11301): Gtk-CRITICAL **: _gtk_container_get_border_width_set: assertion 'GTK_IS_CONTAINER (container)' failed

(redshift-gtk:11301): Gtk-CRITICAL **: gtk_container_set_border_width: assertion 'GTK_IS_CONTAINER (container)' failed

(redshift-gtk:11301): Gtk-CRITICAL **: _gtk_container_set_border_width_set: assertion 'GTK_IS_CONTAINER (container)' failed

(redshift-gtk:11301): Gtk-CRITICAL **: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed
Segmentation fault (core dumped)
[xxxx@mars ~]$

**Comment by frademacher** [comment] 2017-06-26 20:22
I recently hit the same bug: After closing the info dialog with the X window control, the info window stays blank  for all subsequent activations.

I was able to fix this bug when adding the following line of code after self.info_dialog has been initialized in the constructor of the RedshiftStatusIcon class in file statusicon.py (after line 309 in the current stable statusicon.py on redshift's master branch):
`self.info_dialog.connect('delete-event', lambda widget=None, data=None: True)`

When returning True from the "delete-event" handler, this seems to prevent the dialog window's destruction, as the closing event propagation is stopped. And because RedshiftStatusIcon.response_info_cb() still gets called, the dialog is hidden. However, it's instance remains reusable for subsequent calls, i.e. it's content won't be blank anymore. 

I don't now if this is the proper "GTK-ish" fix, but at least it works for me on LinuxMint 18.1 with redshift 1.7. Maybe you can try, if this fixes the bug for you too (and for redshift 1.11) and if so, I'll try to submit a proper pull request?

**Comment by frademacher** [comment] 2017-06-27 06:30
Ah, nevermind. I just came to recognize that this bug is a duplicate of #220, which has already been fixed in PR #315 in basically the same way.

**Comment by jonls** [comment] 2017-07-31 03:36
Thanks for reporting this 👍  @frademacher Yes, it seems like you came to the same solution as #315 which I'm finally getting around to merge. I'm going to merge this solution as part of #491.

**Closed by jonls** 2017-07-31 03:36 UTC
Labels: bug
