### ISSUE TITLE
Allow user to specify time period for Redshift to activate

### ISSUE THREAD

**Issue by mightyspaj** [jonls/redshift#502] opened 2017-08-19 03:32 UTC
You can currently set your location so that Redshift automatically activates at night, but what you *can't* do is set *when* you want Redshift to activate.

This is very useful for users such as myself who work late in the evening. Redshift will automatically activate at sunset (whilst I'm still working), so I have to manually deactivate it. Instead, I should be able to specify what time I want Redshift to activate so that this isn't an issue.

**Comment by jonls** [comment] 2017-08-19 19:10
Thanks! This seems to be a duplicate of #9. Please join the discussion there.

**Closed by jonls** 2017-08-19 19:10 UTC
