### ISSUE TITLE
redshift-gtk doesn't work 

### ISSUE THREAD

**Issue by YogliB** [jonls/redshift#282] opened 2015-12-01 11:00 UTC
This is what I get when I try to run it (v1.10):
[user@user ~]$ redshift-gtk
sys:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
Traceback (most recent call last):
  File "/usr/bin/redshift-gtk", line 26, in <module>
    from redshift_gtk.statusicon import run
  File "/usr/lib/python3.5/site-packages/redshift_gtk/statusicon.py", line 40, in <module>
    from . import utils
  File "/usr/lib/python3.5/site-packages/redshift_gtk/utils.py", line 23, in <module>
    from xdg import BaseDirectory as base
ImportError: No module named 'xdg'

I use Parabola GNU/Linux-Libre and use the Gnome Desktop (3.18.3) on Xorg (1.18).
BTW "redshift" runs perfectly.

**Comment by ThePreviousOne** [comment] 2015-12-12 07:25
run pacman -Qs xdg 
I had a similar problem a few weeks back after a reinstall (Parabola also)
there was a dependency I needed

**Comment by thunderrd** [comment] 2015-12-13 14:25
I have the same message in gentoo.  Having run redshift for a long time now, this is a new message for me, after some recent python updates.  I rebuilt pygobject [and I suggest you try the same], but the message remains after the rebuild.  There appears to be no loss of functionality, though, redshift-gtk starts and works as intended, other than the chatty messages in the tty which appear to be for the developer to fix some code: [?]

thunderrd@Q6600:~$ /usr/bin/redshift-gtk -l 17.416667:102.75 -t 5500:4000 &
[1] 26334
thunderrd@Q6600:~$ /usr/lib64/python3.4/site-packages/redshift_gtk/statusicon.py:32: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GLib, GObject

It would be nice to get the message to go away, and stop spamming the tty/terminal :)

**Comment by jonls** [comment] 2015-12-28 02:41
@YogliB As @ThePreviousOne said, you are missing the Python XDG package.
@thunderrd This was fixed in 442fb9bd5df72e6eb89c34352882ac80f9c9660b. It will be in the next release.

**Closed by jonls** 2015-12-28 02:41 UTC
