### ISSUE TITLE
Manual settings

### ISSUE THREAD

**Issue by jamb0ss** [jonls/redshift#321] opened 2016-02-25 13:53 UTC
Is there any way to adjust the color temperature manually? I work in the dark room during the day and I don't want it to configure the color temperature based on the time and timezone, it has no sense at all. How can I control this settings? Or may be there are some similar tools that give a full access to such settings? Thanks.

**Comment by tyrann** [comment] 2016-02-28 01:44
You can use the "one shot" option with -O. For example, you can type:

    redshift -O 4000

This will set the screen color temperature to 4000 K. To reset the color temperature, type:

    redshift -x

**Comment by jamb0ss** [comment] 2016-02-28 18:42
Can it be done somehow via tray icon? 

Also, what is the difference:
  -o		One shot mode (do not continuously adjust color temperature)
  -O TEMP	One shot manual mode (set color temperature)

In the first case it'll use the color temperature as it would be in normal mode at this time of the day and will not change it, right? In the second case (upper case O) it's clear, thanks.

**Comment by jamb0ss** [comment] 2016-02-28 18:44
It just would be great if there will be any option in GUI mode (tray icon) to set the color temperature manually. It'll cover all use cases I suppose. Just thoughts :)

**Comment by ACinnamonUserInUK** [comment] 2016-05-01 00:23
I find that `redshift -0` and `redshift -r` and `redshift -t` _do not work_. For they take effect momentarily and then the screen reverts. Or, sometimes (and depending on which of the foregoing commands is issued) the screen oscillates between the previous state and the new one. What is happening, I think, is that two instances of redshift are competing with each other!

Also, I don't understand how `redshift-o` (with lowercase 'o') is meant to work!

Finally: is there no way, at the command line, of displaying the _current_ colour temperature? (I need that functionality for a conky.

**Comment by tyrann** [comment] 2016-05-01 00:39
The option ` -0` does not exist, do you mean `-O`? Of course if you have two instance of redshift running together, you're asking for trouble. Try killing all redshift processes and start again.

`redshift -o` allows you to fix the color temperature by disabling continuous adjustment.

As for your last question, it has been answered by @jonls:
"Redshift can't detect the current color temperature, as the color temperature is set through the gamma ramps, and they do not necessarily correspond to a specific color temperature."

**Comment by ACinnamonUserInUK** [comment] 2016-05-01 03:38
tyrann: thanks for your reply.

I did mean `o`; sorry, I mistyped.

Killing all redshift processes requires superuser privileges; for that reason, frequent changes of redshift settings become a bit of a chore. Moreover, isn't changing stuff on the fly what the -r and -o options are for? I am confused.

As to being able to display the current colour temperature: well, couldn't we have redshift at least remember, and be able to output, the last colour temperature that it was used (directly) to set?

As things stand, I have have a conky that always displays the temperature that my redshift.conf files _thinks_ is current, i.e. the colour temperature that will be in operation _so long as_ I have not gone through the ringmarole - so as to temporarily adjust or disable redshift - of killing all redshift processes and then starting a redshift process. (Why do I not use the GUI to suspend redshift? [Because doing so does not work](https://github.com/jonls/redshift/issues/336).)

(Conky screenshot: attached. See towards its right. ![screenshot-area-2016-05-01-043042](https://cloud.githubusercontent.com/assets/9998846/14939933/ae39f288-0f55-11e6-9b33-0f5299278e5e.png)
Relevant part of Conky code: 
`
${if_running redshift}${texeci 3 redshift -p | awk '{printf($3)}'}${font}\`
)

**Comment by tyrann** [comment] 2016-05-01 04:01
> Moreover, isn't changing stuff on the fly what the -r and -o options are for? I am confused.

Yes, but changing stuff on the fly does not mean having several instances running. I was suggesting killing processes in case you had competing instances of redshift. You can check if several instances are running at the same time with `ps aux | grep redshift`

Sadly, I'm not familiar with Conky so I cannot really help you on this. But here is what I know:
If you know your current latitude and longitude parameters, you can call redshift like this:
`redshift -p -l 47:8`
This will give you the following output:
```
Period: Transition (18.54% day)
Color temperature: 3870K
Brightness: 1.00
```
This call will not start an instance of redshift, just display that text. So there must be a way to write a script or cron job that basically calls this at some predefined timestep. Each time it is called, retrieve the output and you will find the current temperature. I hope that helps you.

**Comment by ACinnamonUserInUK** [comment] 2016-05-01 04:19
I think that perhaps when I run redshit it generates two instances (and that this is the cause of the problems). For consider the following.

```
$ sudo killall redshift
$ sudo killall redshift
redshift: no process found
$ ps aux | grep redshift
redshift
```

Then, in another terminal (because running redshift leaves the first one hanging):

```
$ ps aux | grep redshift
[username redacted]  8851  3.5  0.0  18268  2308 ?        SN   05:10   0:00 redshift
[username redacted - same username as above]  8906  0.0  0.0  10416  1648 pts/4    SN+  05:10   0:00 grep --colour=auto redshift
```

**Comment by ACinnamonUserInUK** [comment] 2016-05-01 04:54
There really does seem to be something odd going on. I removed redshift and then reinstalled it, but I am still getting some funny behaviour when I try to disable or reenable Redshift and I get this:

```
$ sudo killall redshift
redshift: no process found
$ sudo killall redshift
redshift: no process found
$ ps aux | grep redshift
nicholas 13877  4.3 10.1 1294800 410016 ?      Sl   05:22   1:07 /usr/lib/firefox/firefox https://github.com/jonls/redshift/issues/321#issuecomment-216014740
nicholas 30008  0.0  0.0  10416  1648 pts/4    SN+  05:48   0:00 grep --colour=auto redshift
```
Now, the first of the entries in that last block output is the browser I am typing this text into. But the second? Surely that should not be there after the `killall`. Nor can I find a process with that id (3008) in any task managers.

**Comment by tyrann** [comment] 2016-05-01 04:59
The second is the grep command recaptured because you called `grep redshift`. Nothing to worry about, I don't thing there is a problem with redshift here.

**Comment by ACinnamonUserInUK** [comment] 2016-05-01 19:40
I really am sorry to go on - and thanks for your reply - but I do think there is a still a problem. For I cannot find a way of disabling redshift without doing a `sudo killall redshift`. For

`redshift -O 6500K`

used at night, or

` ~ $ redshift -O 3500K`

used during the day, seem not to work properly. Rather, what happens, is that the effect redshift has on the screen is indeed disabled but only for a moment; the screen reverts. And the same goes for

`redshift -x`

Moreover, (all) this behaviour occurs even when I have checked (so far as I can) that, before issuing those commands, there is only one instance of Redshift running (and indeed afterwards there seems to be only one version too).

I do hope I am not being dim.

**Comment by tyrann** [comment] 2016-05-01 19:45
Well, then I cannot help you since I don't get this behavior. Are you sure you using the latest version?

**Comment by ACinnamonUserInUK** [comment] 2016-05-01 20:12
I wasn't, most recently, using the latest version. For I had uninstalled it because I had thought I might have installed it *along with* an older version. So I tried, just now, to install the latest version. I'd lost the instructions I'd found that seemed to work. I found some other instructions. I had a lot of trouble with them. Ultimately, they seemed to work, although redshift does not show up in my package manager. It does run commands though. And . . the same situation obtains as before. Changes don't stick. I give up.

**Comment by jonls** [comment] 2017-01-08 21:00
I'm not sure what is causing this but there could be other applications that are resetting the gamma ramps. I think this has been reported in the past when using nvidia proprietary drivers but it could be something else too.

**Comment by jonls** [comment] 2017-01-08 21:03
@jamb0ss Sorry, I just realized that the initial issue here was just a request for manual settings. This has been suggested before in #9. Please continue the discussion there.

@ACinnamonUserInUK Please open a separate issue if you're still interested in finding a solution.

**Closed by jonls** 2017-01-08 21:03 UTC
