### ISSUE TITLE
Tint colour cumulates on AMD GPUs

### ISSUE THREAD

**Issue by Quoor8ee** [jonls/redshift#623] opened 2018-05-28 21:49 UTC
Another odd behaviour of redshift on recent AMD hardware.
When I run `redshift -O 3000`, e. g., the screen is tinted in a reddish yellow, as it should. But when I execute the command _a second time_, the colouration is _repeated_, i. e. the screen becomes a deeper and deeper orange with each execution of redshift. I can even create a greenish hue by altering with the application of `redshift -O 10000`.
Hardware: Polaris RX 550 (PCIe/Desktop),  Raven Ridge Vega8 (Notebook IGP)
Linux 4.17-rc6, linux-firmware-git 20180525.7518922, xf86-video-amdgpu 18.0.1

**Comment by grmat** [comment] 2018-05-29 09:31
duplicate of #513 

use additional `-P` switch for oneshot mode

**Closed** 2018-05-29 16:45 UTC
