### ISSUE TITLE
It's possible to start two simulaneous instances of Redshift

### ISSUE THREAD

**Issue by JBYoshi** [jonls/redshift#366] opened 2016-09-23 03:07 UTC
If I open Redshift from the menu, then open it again, I get two instances of Redshift. Could you change it to prevent multiple instances?

I'm using the `redshift` and `redshift-gtk` packages, both version `1.10.5ubuntu1`, on Linux Mint via the official Ubuntu repository.

**Comment by EvertonMelo** [comment] 2016-09-29 20:15
Hi, 
The Redshit it too:
redshift ( binary and aplication, commandline and integratation redshift-gtk  ) 
and 
redshift-gtk ( Adjusts the color temperature of your screen with GTK+ integration.) 

They are distinct.

**Comment by jonls** [comment] 2016-10-01 01:32
@JBYoshi Currently, it is necessary to run multiple instances of redshift with some configurations (e.g. with two screens where different settings are desired for each screen). For this reason I don't think we can disallow multiple instances just yet.

**Comment by JBYoshi** [comment] 2016-10-01 21:21
Since the processes are separate, why not just prevent `redshift-gtk` from starting a new `redshift` process each time?

**Comment by jonls** [comment] 2016-10-02 04:51
Right now you may need two instances of `redshift` (optionally started through `redshift-gtk`) to control two screens separately. I'm not sure what you mean when you say that we can just prevent `redshift-gtk` from starting a new process. What would `redshift-gtk` do without a `redshift` process?

**Comment by JBYoshi** [comment] 2016-10-03 11:12
I mean to only start a new `redshift` process when one isn't already started, and to use any existing process(es) when available.

**Comment by fb87** [comment] 2016-11-08 23:55
Duplicate of #218.

**Comment by jonls** [comment] 2017-01-08 20:05
@fbruetting Thanks.

I'm closing this issue. Please continue any constructive discussion towards fixing this in #218.

**Closed by jonls** 2017-01-08 20:05 UTC
Labels: duplicate
