### ISSUE TITLE
possible to manually set the times to go blue and red? 

### ISSUE THREAD

**Issue by SanjeevKSharma** [jonls/redshift#463] opened 2017-05-25 00:31 UTC
I need to get to sleep way before sunset so is it possible to just set arbitrary times when "sundown" should be?

**Comment by draeath** [comment] 2017-05-31 21:36
Yes, kind of.

Set in the config file elevation-high and elevation-low. Elevation-high is the sun azimuth at the start of the day-night transition, and elevation-low is the azimuth at the end of the transition. These values are in degrees, and can be negative. This isn't really documented, but you can kind of get an idea of what they do by looking at these spots in the code:

https://github.com/jonls/redshift/blob/release-1.10/src/redshift.c#L285-L290
https://github.com/jonls/redshift/blob/release-1.10/src/solar.h#L30
https://github.com/jonls/redshift/blob/release-1.10/src/solar.c#L36

**Comment by draeath** [comment] 2017-05-31 21:38
You can also see some discussion and other workarounds in #9

**Comment by jonls** [comment] 2017-07-26 21:37
@SanjeevKSharma Thanks for the suggestion and thanks to @draeath for the workarounds. As mentioned, this is a duplicate of #9 so I will close this issue. Please continue the discussion of this issue there.

**Closed by jonls** 2017-07-26 21:37 UTC
