### ISSUE TITLE
redshift-gtk.service: Failed with result 'core-dump'

### ISSUE THREAD

**Issue by fictionic** [jonls/redshift#592] opened 2018-03-04 05:17 UTC
Launching `redshift-gtk` manually works fine. But when I try to run it with `systemctl --user start redshift-gtk`, it doesn't start, and I get a long stack trace in `systemctl --user status redshift-gtk`.

```
Mar 03 21:11:53 dylan-thinkpad systemd[510]: redshift-gtk.service: Failed with result 'core-dump'.
Mar 03 21:11:53 dylan-thinkpad systemd-coredump[6496]: Process 6473 (redshift-gtk) of user 1000 dumped core.
                                                       
                                                       Stack trace of thread 6473:
                                                       #0  0x00007f37c4ce5809 n/a (libgtk-3.so.0)
                                                       #1  0x00007f37c4b739c9 n/a (libgtk-3.so.0)
                                                       #2  0x00007f37c4b89c85 n/a (libgtk-3.so.0)
                                                       #3  0x00007f37c4b74d7d n/a (libgtk-3.so.0)
                                                       #4  0x00007f37c4b89bc0 n/a (libgtk-3.so.0)
                                                       #5  0x00007f37c4b89c16 n/a (libgtk-3.so.0)
                                                       #6  0x00007f37c4b75714 n/a (libgtk-3.so.0)
                                                       #7  0x00007f37cc94bc98 g_type_create_instance (libgobject-2.0.so.0)
                                                       #8  0x00007f37cc92b729 n/a (libgobject-2.0.so.0)
                                                       #9  0x00007f37cc92cf6d g_object_new_with_properties (libgobject-2.0.so.0)
                                                       #10 0x00007f37cc92da22 g_object_new (libgobject-2.0.so.0)
                                                       #11 0x00007f37c4b923ab n/a (libgtk-3.so.0)
                                                       #12 0x00007f37c4d7dafa n/a (libgtk-3.so.0)
                                                       #13 0x00007f37cc94bc98 g_type_create_instance (libgobject-2.0.so.0)
                                                       #14 0x00007f37cc92b729 n/a (libgobject-2.0.so.0)
                                                       #15 0x00007f37cc92d25d g_object_newv (libgobject-2.0.so.0)
                                                       #16 0x00007f37ccdb0f8f n/a (_gi.cpython-36m-x86_64-linux-gnu.so)
                                                       #17 0x00007f37ccdb8972 n/a (_gi.cpython-36m-x86_64-linux-gnu.so)
                                                       #18 0x00007f37ce253284 n/a (libpython3.6m.so.1.0)
                                                       #19 0x00007f37ce206ee5 _PyObject_FastCallDict (libpython3.6m.so.1.0)
                                                       #20 0x00007f37ce223e4e n/a (libpython3.6m.so.1.0)
                                                       #21 0x00007f37ce1b7b5a _PyEval_EvalFrameDefault (libpython3.6m.so.1.0)
                                                       #22 0x00007f37ce22336b _PyFunction_FastCallDict (libpython3.6m.so.1.0)
                                                       #23 0x00007f37ce2070bf _PyObject_FastCallDict (libpython3.6m.so.1.0)
                                                       #24 0x00007f37ce207e03 _PyObject_Call_Prepend (libpython3.6m.so.1.0)
                                                       #25 0x00007f37ce207eeb PyObject_Call (libpython3.6m.so.1.0)
                                                       #26 0x00007f37ce22b29b n/a (libpython3.6m.so.1.0)
                                                       #27 0x00007f37ce253284 n/a (libpython3.6m.so.1.0)
                                                       #28 0x00007f37ce206ee5 _PyObject_FastCallDict (libpython3.6m.so.1.0)
                                                       #29 0x00007f37ce223e4e n/a (libpython3.6m.so.1.0)
                                                       #30 0x00007f37ce1b7b5a _PyEval_EvalFrameDefault (libpython3.6m.so.1.0)
                                                       #31 0x00007f37ce222a1e n/a (libpython3.6m.so.1.0)
                                                       #32 0x00007f37ce223a8f n/a (libpython3.6m.so.1.0)
                                                       #33 0x00007f37ce223dde n/a (libpython3.6m.so.1.0)
                                                       #34 0x00007f37ce1b7b5a _PyEval_EvalFrameDefault (libpython3.6m.so.1.0)
                                                       #35 0x00007f37ce2242c8 PyEval_EvalCodeEx (libpython3.6m.so.1.0)
                                                       #36 0x00007f37ce1b76ec PyEval_EvalCode (libpython3.6m.so.1.0)
                                                       #37 0x00007f37ce289f84 n/a (libpython3.6m.so.1.0)
                                                       #38 0x00007f37ce28c751 PyRun_FileExFlags (libpython3.6m.so.1.0)
                                                       #39 0x00007f37ce28c954 PyRun_SimpleFileExFlags (libpython3.6m.so.1.0)
                                                       #40 0x00007f37ce28270b Py_Main (libpython3.6m.so.1.0)
                                                       #41 0x0000562e4ab28c39 main (python3.6)
                                                       #42 0x00007f37ce61cf4a __libc_start_main (libc.so.6)
                                                       #43 0x0000562e4ab28dba _start (python3.6)
                                                       
                                                       Stack trace of thread 6491:
                                                       #0  0x00007f37ce6e797b __poll (libc.so.6)
                                                       #1  0x00007f37cc64bff3 n/a (libglib-2.0.so.0)
                                                       #2  0x00007f37cc64c10e g_main_context_iteration (libglib-2.0.so.0)
                                                       #3  0x00007f37cc64c162 n/a (libglib-2.0.so.0)
                                                       #4  0x00007f37cc67426a n/a (libglib-2.0.so.0)
                                                       #5  0x00007f37ce9ba08c start_thread (libpthread.so.0)
                                                       #6  0x00007f37ce6f1e7f __clone (libc.so.6)
Mar 03 21:11:53 dylan-thinkpad systemd[510]: redshift-gtk.service: Service hold-off time over, scheduling restart.
Mar 03 21:11:53 dylan-thinkpad systemd[510]: redshift-gtk.service: Scheduled restart job, restart counter is at 5.
Mar 03 21:11:53 dylan-thinkpad systemd[510]: Stopped Redshift display colour temperature adjustment (GUI).
Mar 03 21:11:53 dylan-thinkpad systemd[510]: redshift-gtk.service: Start request repeated too quickly.
Mar 03 21:11:53 dylan-thinkpad systemd[510]: redshift-gtk.service: Failed with result 'core-dump'.
Mar 03 21:11:53 dylan-thinkpad systemd[510]: Failed to start Redshift display colour temperature adjustment (GUI).
```

I'm on Arch Linux. Kernel 4.15.6-1. Redshift 1.11-5.

**Comment by jonls** [comment] 2018-05-07 02:37
Duplicate of #265

**Closed by jonls** 2018-05-07 02:37 UTC
