### ISSUE TITLE
Issues with Redshift on startup and without internet

### ISSUE THREAD

**Issue by potholiday** [jonls/redshift#288] opened 2016-01-01 03:59 UTC
I have installed redshift in ubuntu 14.04 system and I came across these two problems in my system.

1)for past few months redshift is not running automatically from startup. Everytime on fresh reboot i have to manually enable redshift through command line.

2)Redshift doesn’t work  without internet. I only get some times internet and because of this most of the time redshift is disabled. How can i enable redshift without internet

**Comment by auscompgeek** [comment] 2016-01-28 23:25
Redshift starts fine for me on startup. Are you sure Redshift is in your autostarts?

Yes, GeoClue requires an internet connection to get your location in most cases (this is by design). The manual location provider exists for those that can't use GeoClue.

**Comment by potholiday** [comment] 2016-01-29 06:14
@auscompgeek  I have added redshift manually to my ** startup applications** I have tried these two codes `gtk-redshift` and `redshift-gtk` but still redshift is not working in startup.

I have successfully changed the location in my config file` ~/.config/redshift.conf`  but still without internet redshift will not work. I dont know why ?

*system=ubuntu 14.

**Comment by jonls** [comment] 2017-08-19 19:25
This may be fixed by #500 in the next release. Please open a new issue if the issue persists in the next release.

**Closed by jonls** 2017-08-19 19:25 UTC
