### ISSUE TITLE
redshift-gtk no info and crash.

### ISSUE THREAD

**Issue by JulianLai** [jonls/redshift#467] opened 2017-06-02 10:10 UTC
OS: antergos
https://youtu.be/kb9EgHJFzF0

**Comment by EvertonMelo** [comment] 2017-07-18 16:18
Please describe the environment in question:

'uname -a

'redshift -v

Please describe at what time the error occurs.

**Comment by Roald87** [comment] 2017-08-15 20:06
I have the same issue sometimes. When I wake my system from stand-by the color temperature is not changed. I then try to check _Info_, but that is than either empty or it crashes and it displays a geoclue2 message I believe. Will update when I get it again.

    uname -a
   
    Linux roald-XPS-13-9360 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```
redshift -v

Trying location provider `geoclue2'...
Using provider `geoclue2'.
Location: 53.23 N, 6.58 E
Temperatures: 5500K at day, 3500K at night
Solar elevations: day above 3.0, night below -6.0
Brightness: 1.00:1.00
Gamma (Daytime): 1.000, 1.000, 1.000
Gamma (Night): 1.000, 1.000, 1.000
Using method `randr'.
Status: Enabled
Period: Night
Color temperature: 6470K
Brightness: 1.00
Color temperature: 6440K
Color temperature: 6410K
...
```

**Comment by jonls** [comment] 2017-08-15 21:28
Could this be a duplicate of #220?

**Comment by Roald87** [comment] 2017-08-15 21:31
@jonls Don't think so. I've never had a very very small window. My window size is the same as in the video, which I would call a normal window size.

**Comment by jonls** [comment] 2017-08-15 21:33
@Roald87 Ok. I think the bug in #220 does not necessarily show itself as a small window. The question is whether it can be reproduced by closing the window using the X in the top bar.

**Comment by Roald87** [comment] 2017-08-15 21:35
@jonls Yes. I closed the window by clicking on the X and then opened the _Info_ panel again, which showed an empty panel.

**Comment by jonls** [comment] 2017-08-15 21:36
@Roald87 Thanks! In that case it has already been fixed and will be in the next release.

**Comment by jonls** [comment] 2017-08-15 21:37
@Roald87 Please open another issue if the Geoclue2 error appears again.

**Closed by jonls** 2017-08-15 21:37 UTC
Labels: bug
