### ISSUE TITLE
DRM adjustment method prevents changing framebuffer console colors

### ISSUE THREAD

**Issue by remexre** [jonls/redshift#616] opened 2018-05-20 16:50 UTC
redshift works in the framebuffer with the drm adjustment method. However, setting framebuffer console colors by writing to `/sys/module/vt/parameters/default_{red,grn,blu}` and running `reset` doesn't work while redshift is running. `systemctl stop --user redshift; printf '\e]R\ec'; systemctl start --user redshift` applies the change properly, though.

**Comment by maandree** [comment] 2018-05-20 17:55
Duplicate of #441

**Comment by jonls** [comment] 2018-05-21 00:29
Thanks for reporting, apparently this is a known limitation.

**Closed by jonls** 2018-05-21 00:29 UTC
