### ISSUE TITLE
Redshift doesn't change screen color on 16.04

### ISSUE THREAD

**Issue by simontheflutist** [jonls/redshift#357] opened 2016-08-15 05:21 UTC
I'm using Ubuntu 16.04 LTS, latest redshift and redshift-gtk. When I start redshift it gets location from geoclue2, and all appears well in the console, except the screen's color does not change. I'm not sure what other information to give (please ask). I can't remember exactly when or why it went wrong.

**Comment by chiraag-nataraj** [comment] 2016-08-15 14:35
Possible duplicate of #354

**Comment by chiraag-nataraj** [comment] 2016-08-15 14:37
@simontheflutist try suspending and resuming your laptop to see if screen color changes then.

**Comment by simontheflutist** [comment] 2016-08-15 19:46
Resuming my computer this morning, I see that redshift is active; however, it should have a cool color at this time of the day. I rebooted and now it's fine; but I want to wait until tonight to see.

**Comment by Ghedeon** [comment] 2016-08-17 20:26
Same issue, no errors and nothing is happening. Can't see any effect from suspending/resuming.

Arch linux 4.7-1
Gnome 3.20.3
Dell XPS 15 9550, Intel Corporation HD Graphics 530 (rev 06)

**Comment by simontheflutist** [comment] 2016-08-18 04:26
Nevermind, I think it's a duplicate of #354.

**Comment by zxz054321** [comment] 2016-08-25 12:00
Doesn't work at all
ubuntu 16.04

**Comment by jonls** [comment] 2016-10-01 02:03
Ok, it seems that the issue as reported by @simontheflutist was a duplicate of #354. If there is still any problem that is _not_ related to #354 please open a separate issue.

**Closed by jonls** 2016-10-01 02:03 UTC
